import { AsyncLocalStorage } from 'node:async_hooks';
import pg from 'pg';

export function translateSQL(sql) {
  if (/^\s*PRAGMA\b/i.test(sql) && !sql.includes('CREATE TABLE')) return null;
  let text = sql.replace(/PRAGMA[^;]*;/g, '')
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    // SQLite integers are 64-bit; epoch milliseconds and shuffle seeds exceed int32.
    .replace(/\bINTEGER\b/g, 'BIGINT')
    .replace(/\bREAL\b/g, 'DOUBLE PRECISION')
    .replace(/date\('now','localtime'\)/g, "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD')")
    .replace(/instr\(s\.exam_id, '::'\)/g, "strpos(s.exam_id, '::')")
    .replace(/sqlite_master/g, 'information_schema.tables')
    .replace(/type = 'table' AND name NOT LIKE 'sqlite_%'/g, "table_schema = 'public'")
    .replace(/SELECT name FROM information_schema.tables WHERE type = 'table' AND name = \?/g,
      "SELECT table_name AS name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = ?");
  let index = 0;
  text = text.replace(/\?/g, () => `$${++index}`);
  if (/^\s*INSERT INTO users\b/i.test(text) && !/RETURNING/i.test(text)) text += ' RETURNING id';
  return text;
}

export async function createPostgresDatabase(connectionString, injectedPool) {
  if (!connectionString && !injectedPool) throw new Error('DATABASE_URL is required for cloud storage');
  const pool = injectedPool || new pg.Pool({ connectionString, max: 4, connectionTimeoutMillis: 15000,
    idleTimeoutMillis: 30000, statement_timeout: 30000 });
  // SQL COUNT/SUM return int8; counts are bounded by this application's data limits.
  pg.types.setTypeParser(20, value => Number(value));
  pool.on?.('error', () => console.error('Database pool connection error'));
  const context = new AsyncLocalStorage();
  async function query(sql, values = []) {
    return (context.getStore()?.client || pool).query(sql, values);
  }
  return {
    withContext: callback => context.run({}, callback),
    async exec(sql) {
      if (sql === 'BEGIN IMMEDIATE') {
        const state = context.getStore();
        if (!state) throw new Error('Transaction context missing');
        state.client = await pool.connect();
        try { await state.client.query('BEGIN'); }
        catch (error) { state.client.release(); delete state.client; throw error; }
        return;
      }
      if (sql === 'COMMIT' || sql === 'ROLLBACK') {
        const state = context.getStore();
        if (!state?.client) return;
        try { await state.client.query(sql); }
        finally { state.client.release(); delete state.client; }
        return;
      }
      const translated = translateSQL(sql);
      if (translated) await query(translated);
    },
    prepare(sql) {
      if (sql === 'PRAGMA integrity_check') return { get: async () => { await query('SELECT 1'); return { integrity_check: 'ok' }; } };
      const translated = translateSQL(sql);
      return {
        get: async (...args) => (await query(translated, args)).rows[0],
        all: async (...args) => (await query(translated, args)).rows,
        run: async (...args) => {
          const result = await query(translated, args);
          return { changes: result.rowCount, lastInsertRowid: result.rows[0]?.id };
        }
      };
    },
    close: () => pool.end()
  };
}
